// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGMjNOGQ4CKpjoedSlaPYQYK-T6UibXuU',
    appId: '1:339901482541:web:ece5b06cf682462e6e5aa4',
    messagingSenderId: '339901482541',
    projectId: 'car-rental-system-61f97',
    authDomain: 'car-rental-system-61f97.firebaseapp.com',
    storageBucket: 'car-rental-system-61f97.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyHybOY7A5a555WosratlkOl1zdZX8kfo',
    appId: '1:339901482541:android:96c0331d103a9c816e5aa4',
    messagingSenderId: '339901482541',
    projectId: 'car-rental-system-61f97',
    storageBucket: 'car-rental-system-61f97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtP5Le3HVwXi7th8fnEZua-qsN6eFDQO4',
    appId: '1:339901482541:ios:64041fc42444e5616e5aa4',
    messagingSenderId: '339901482541',
    projectId: 'car-rental-system-61f97',
    storageBucket: 'car-rental-system-61f97.firebasestorage.app',
    iosBundleId: 'com.manira.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtP5Le3HVwXi7th8fnEZua-qsN6eFDQO4',
    appId: '1:339901482541:ios:579b0d708c872cf06e5aa4',
    messagingSenderId: '339901482541',
    projectId: 'car-rental-system-61f97',
    storageBucket: 'car-rental-system-61f97.firebasestorage.app',
    iosBundleId: 'com.example.carRentalSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGMjNOGQ4CKpjoedSlaPYQYK-T6UibXuU',
    appId: '1:339901482541:web:11d20c1b918bf74a6e5aa4',
    messagingSenderId: '339901482541',
    projectId: 'car-rental-system-61f97',
    authDomain: 'car-rental-system-61f97.firebaseapp.com',
    storageBucket: 'car-rental-system-61f97.firebasestorage.app',
  );
}
